#This is based on http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/
version: '3'
 
services:
  pihole:
    container_name: pihole-vlan
    image: pihole/pihole:latest
    hostname: pihole                       # <-- container's hostname
    domainname: jolania.in               # <-- domain name of your pihole container
    mac_address:  66:e5:3e:6f:0e:0d         # <-- replace with a random mac address,
 
    # The above should be something like e2:09:0e:d4:40:66. This is NOT the physical server.
    # You can use this site to generate a random mac address(pick top number): https://www.hellion.org.uk/cgi-bin/randmac.pl?scope=local&type=unicast
   
    cap_add:
      - NET_ADMIN
    networks:
      macvlan0:
        ipv4_address: 192.168.0.103         # <-- Replace with an unused ip address on your network to assign to the Pi-hole instance (not ip address of the physical server)
    dns:
      - 127.0.0.1
      - 8.8.8.8      #<-- Replace as secondary DNS - can change to whatever you want, this is Cloudflare
      - 1.1.1.1      #<-- Replace
 
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.0.103        # <-- Revise to match ipv4_address above)
      VIRTUAL_HOST: pihole.jolania.in  # <-- Revise to match hostname + domainname)
      #WEBPASSWORD: ""                   # <-- Add password (if required)
    restart: unless-stopped
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./etc/dnsmasq.d:/etc/dnsmasq.d
      - ./backups/:/backups/
      
networks:
  macvlan:   # externally created network (later in article)
    external: true
  